spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/trading
    username: trading
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
